### ISSUE TITLE
Handle FOUC - `:defined`?

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#11]
Custom elements take time to get upgraded, which means we might see a flash of unstyled content.

https://developers.google.com/web/fundamentals/web-components/customelements#prestyle

> Before an element is upgraded you can target it in CSS using the :defined pseudo-class. This is useful for pre-styling a component. For example, you may wish to prevent layout or other visual FOUC by hiding undefined components and fading them in when they become defined.

@chanar thoughts?

**Comment by chanar** [comment]
There is option to use unresolved on body tag. `<body unresolved>`

This will smooth load the view but it means a small (currently half a second) wait until view is rendered. Webpack has option to load js "when needed" so when this first (unresolved) option becomes too bearing, we could try that option.

**Comment by lkraav** [comment]
I guess we will see how the loading experience will be on WP, soon. Further decisions to be made then.

**Comment by lkraav** [comment]
Tested, this works exactly as per Google docs and desired:

```css
cxl-institute-layout:not(:defined) {
	/* Pre-style, give layout, replicate app-drawer's eventual styles, etc. */
	display: block;
	height: 100vh;
	opacity: 0;
	transition: opacity 0.3s ease-in-out;
}
```

@chanar can layout component get this, or needs to be part of app-level CSS?
